table 'dimensional kpi'
	lineageTag: 47d74ea1-80e9-4d10-9ef1-f5c031452778

	measure measure_target = ```
			
			IF(
			    ISFILTERED('dimensional kpi'[month]) || ISFILTERED('dimensional dim_time'[time_year]), 
			    SUM('dimensional kpi'[target]), 
			    0
			)
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 73866cbd-8537-4d1b-a580-5614f80e7bfa

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure measure_total_revenue = ```
			
			IF(
			    ISFILTERED('dimensional kpi'[month]) || ISFILTERED('dimensional dim_time'[time_year]),
			    SUM('dimensional kpi'[total_revenue]), 
			    0
			)
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 119f7bce-b935-4d43-b462-e58c5750b61e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column month
		dataType: int64
		formatString: 0
		lineageTag: c409ccb3-71f8-4c84-b6af-47bba88b7155
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = User

	column total_revenue
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: e08e5617-d89a-433e-be1d-3c8c0c5fba81
		summarizeBy: sum
		sourceColumn: total_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column target
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 7c448d66-f693-48f2-97af-ac38583719ba
		summarizeBy: sum
		sourceColumn: target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition 'dimensional kpi' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost:5433", "JJBike"),
				    dimensional_kpi = Source{[Schema="dimensional",Item="kpi"]}[Data]
				in
				    dimensional_kpi

