INSERT INTO Relational.products(product_name, product_price) VALUES ('Rim 29 Mountain Bike Endorphine 6.3 - 24 Speed - Shimano - Aluminum', 8852.00);
INSERT INTO Relational.products(product_name, product_price) VALUES ('Altools Stroll Rim 26 Disc Brake 21 Speed Bicycle', 9201.00);
INSERT INTO Relational.products(product_name, product_price) VALUES ('Gts Advanced 1.0 Rim 29 Disc Brake Shimano Rear Derailleur 24 Speed Bicycle', 4255.00);
INSERT INTO Relational.products(product_name, product_price) VALUES ('Trinc Shimano Derailleurs Rim 29 Disc Brake 24 Speed Bicycle', 7658.00);
INSERT INTO Relational.products(product_name, product_price) VALUES ('Gometws Endorphine 7.3 - Shimano Aluminum Rim 29 - 24 Speed Bicycle', 2966.00);
INSERT INTO Relational.products(product_name, product_price) VALUES ('Gometws Endorphine 6.1 Shimano Aluminum Rim 26 - 21 Speed Bicycle', 2955.00);
INSERT INTO Relational.products(product_name, product_price) VALUES ('Gometws Endorphine 2.0 Helmet', 155.00);
INSERT INTO Relational.products(product_name, product_price) VALUES ('Gometws Sports Cycling Glove', 188.00);
INSERT INTO Relational.products(product_name, product_price) VALUES ('Predactor 3Xu Pro Cycling Shorts', 115.00);
INSERT INTO Relational.products(product_name, product_price) VALUES ('Predactor 3Xu Multiplied Cycling Jersey', 135.00);
